### ISSUE TITLE
Returning 0 results in blank

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/FieldtypeRuntimeOnly#1]
This isn't because of this module, but rather because PW's template render() method, but it can be a problem if you're using this module to calculate runtime values and the result is `0` or even a string `'0'`.

Not sure whether this should be filed a PW core bug or not. Any thoughts?

**Comment by adrianbj** [comment]
Hacky workaround is to prepend a non-breaking space before the returned value.

**Comment by Toutouwai** [comment]
Shouldn't template files echo values rather than return them?

This is working for me in my rendered file:

```php
<?php namespace ProcessWire;
echo 1 - 1;
```

![2019-02-15_163803](https://user-images.githubusercontent.com/1538852/52833070-17e40c00-3140-11e9-937b-21edb33d476c.png)

**Comment by adrianbj** [comment]
Haha - good one. I was converting my code from Kongondo's module which needs `return`. You're right of course - `echo` works.

I didn't realize because `return` works when it's not `0` that is returned.
